/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SIDOSmain.java
 *
 * Created on Feb 13, 2013, 8:48:25 PM
 */
package gui;

import javax.swing.ButtonGroup;

/**
 *
 * @author as888211
 */
public class SIDOSmain extends javax.swing.JFrame {

    /** Creates new form SIDOSmain */
    public SIDOSmain() {
        initComponents();
        customModification();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createAgentDialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        agentRB1 = new javax.swing.JRadioButton();
        agentRB2 = new javax.swing.JRadioButton();
        agentRB3 = new javax.swing.JRadioButton();
        agentSettingsPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        javax.swing.JPanel mainPanel = new javax.swing.JPanel();
        splitPaneMain = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        agentListTree = new javax.swing.JTree();
        rightSplitPane = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newItem = new javax.swing.JMenuItem();
        agentMenu = new javax.swing.JMenu();
        newAgentItem = new javax.swing.JMenuItem();

        createAgentDialog.setTitle("Create New Agent");
        createAgentDialog.setAlwaysOnTop(true);

        jLabel1.setText("Select agent type");

        agentRB1.setText("Schema Agent");

        agentRB2.setText("Ontology Agent");

        agentRB3.setText("Semantic Agent");
        agentRB3.setToolTipText("");

        javax.swing.GroupLayout agentSettingsPaneLayout = new javax.swing.GroupLayout(agentSettingsPane);
        agentSettingsPane.setLayout(agentSettingsPaneLayout);
        agentSettingsPaneLayout.setHorizontalGroup(
            agentSettingsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );
        agentSettingsPaneLayout.setVerticalGroup(
            agentSettingsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        jLabel2.setText("Agent Settings");

        javax.swing.GroupLayout createAgentDialogLayout = new javax.swing.GroupLayout(createAgentDialog.getContentPane());
        createAgentDialog.getContentPane().setLayout(createAgentDialogLayout);
        createAgentDialogLayout.setHorizontalGroup(
            createAgentDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAgentDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createAgentDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agentSettingsPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGroup(createAgentDialogLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(createAgentDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(agentRB2)
                            .addComponent(agentRB1)
                            .addComponent(agentRB3)))
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        createAgentDialogLayout.setVerticalGroup(
            createAgentDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAgentDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agentRB1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agentRB2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agentRB3)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agentSettingsPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIDOS - Semantic Integration of Heterogeneous Datamodels");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(1000, 800));

        splitPaneMain.setDividerLocation(250);
        splitPaneMain.setResizeWeight(0.2);
        splitPaneMain.setToolTipText("");
        splitPaneMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        leftPanel.setFocusTraversalPolicyProvider(true);

        agentListTree.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Active Agents");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Schema Agent");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Ontology Agent");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Semantic Agent");
        treeNode1.add(treeNode2);
        agentListTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(agentListTree);

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );

        splitPaneMain.setLeftComponent(leftPanel);

        rightSplitPane.setDividerLocation(500);
        rightSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        rightSplitPane.setResizeWeight(0.8);

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder("Console"));
        jScrollPane1.setViewportView(jTextArea1);

        rightSplitPane.setBottomComponent(jScrollPane1);
        rightSplitPane.setLeftComponent(jTabbedPane1);

        splitPaneMain.setRightComponent(rightSplitPane);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPaneMain, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPaneMain, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );

        fileMenu.setText("File");

        newItem.setText("New Project");
        newItem.setToolTipText("Create a new data integration project");
        fileMenu.add(newItem);

        menuBar.add(fileMenu);

        agentMenu.setText("Agents");
        agentMenu.setToolTipText("");

        newAgentItem.setText("Create new Agent");
        agentMenu.add(newAgentItem);

        menuBar.add(agentMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree agentListTree;
    private javax.swing.JMenu agentMenu;
    private javax.swing.JRadioButton agentRB1;
    private javax.swing.JRadioButton agentRB2;
    private javax.swing.JRadioButton agentRB3;
    private javax.swing.JPanel agentSettingsPane;
    private javax.swing.JDialog createAgentDialog;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem newAgentItem;
    private javax.swing.JMenuItem newItem;
    private javax.swing.JSplitPane rightSplitPane;
    private javax.swing.JSplitPane splitPaneMain;
    // End of variables declaration//GEN-END:variables
    private ButtonGroup createAgentRBGroup = new ButtonGroup();

    private void customModification() {
        createAgentRBGroup.add(agentRB1);
        createAgentRBGroup.add(agentRB2);
        createAgentRBGroup.add(agentRB3);
        agentRB1.setSelected(true);
        
        newItem.addActionListener(Session.getInstance().getActionListener(1));
        newAgentItem.addActionListener(Session.getInstance().getActionListener(2));
    }
}
